// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZY0qiBY1v3S4X0jOiFa52Tt99i4dPkY',
    appId: '1:293411020526:web:3ad569f73e8ef238e81dff',
    messagingSenderId: '293411020526',
    projectId: 'marihan-todo-app',
    authDomain: 'marihan-todo-app.firebaseapp.com',
    storageBucket: 'marihan-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAweIEZqhqnW8FwwEjhP3aP0nymeLE3c',
    appId: '1:293411020526:android:bc2451f78907509ee81dff',
    messagingSenderId: '293411020526',
    projectId: 'marihan-todo-app',
    storageBucket: 'marihan-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2rxXHfyPPXsF8UJ26t6XHL275bOgQgLs',
    appId: '1:293411020526:ios:2a21abca63bc717ee81dff',
    messagingSenderId: '293411020526',
    projectId: 'marihan-todo-app',
    storageBucket: 'marihan-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
